spring:
  application:
    name: user-manage-userservices
  datasource:
    url: jdbc:mysql://218.199.102.33:3307/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: shuaijun123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


# Dubbo Config properties
dubbo:
  application:
    id: user-manage-user
    name: user-manage-user
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://218.199.102.33:2181