spring:
  application:
    name: cinema-manage-services
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://218.199.102.33:3307/cinema_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: shuaijun123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

# Dubbo Config properties
dubbo:
  application:
    id: cinema-manage-services
    name: cinema-manage-services
    qos-enable: false
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://218.199.102.33:2181