spring:
  application:
    name: platform-gateway
server:
  port: 8080
  tomcat:
    max-threads: 100

# Dubbo Config properties
dubbo:
  application:
    id: user-manage-gateway
    name: user-manage-gateway
  protocol:
    name: dubbo
  registry:
    address: zookeeper://218.199.102.33:2181

rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

auth:
  token:
    name: X-Token
  key:
    name: RandomKey

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 36000      #单位:秒
  auth-path: login         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /user/register,/user/check #忽略列表