spring:
  application:
    name: film-userservices
  datasource:
    url: jdbc:mysql://218.199.102.33:3307/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: shuaijun123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



# Dubbo Config properties
dubbo:
  application:
    id: film-userservices
    name: film-userservices
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://218.199.102.33:2181